fix base URL problems
istio/istio-events pull request #10
Opened 2024-02-29 07:26 UTC by rootsongjc

This is the quickest way to fix the links in the archived 2021 and 2022 pages, as these two campaigns have been archived and I understand that the pages will rarely be updated in the future, which will keep the Hugo version intact. https://github.com/istio/istio.io/issues/14665

The `canonifyURLs = true` configuration I added to Hugo's config file may be removed in the future. https://github.com/gohugoio/hugo/issues/4733

If you don't fix URLs this way, you'll need to make changes to the code in the theme or to the speakers configuration, which is a lot of work.

2024-02-29 07:39 UTC, craigbox commented
OK, the good news is this: _we don't seem to use the lightbox plugin at all!_

We can remove `jquery.fancybox.js` and code that imports it.

Then, if we `s_/istiocon-2021/_/_g` throughout (except the baseURL directive of course) it looks like both 2021 and 2022 will build correctly.

2024-02-29 07:39 UTC, craigbox requested changes

2024-02-29 07:39 UTC, craigbox commented on 2021/config.toml
> +canonifyURLs = true
```suggestion

```

don't need it twice

2024-02-29 09:35 UTC, craigbox commented
Does the background (hero) image load for you?

<img width="1047" alt="Screenshot 2024-02-29 at 10 35 14 PM" src="https://github.com/istio/istio-events/assets/132510/4b9e9ea2-c9d1-41ee-9b21-dfd3c3a54290">

vs 
https://events.istio.io/istiocon-2021/

2024-02-29 10:07 UTC, rootsongjc commented
> Does the background (hero) image load for you?
> 
> <img alt="Screenshot 2024-02-29 at 10 35 14 PM" width="1047" src="https://private-user-images.githubusercontent.com/132510/308871575-4b9e9ea2-c9d1-41ee-9b21-dfd3c3a54290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMDE0NjAsIm5iZiI6MTcwOTIwMTE2MCwicGF0aCI6Ii8xMzI1MTAvMzA4ODcxNTc1LTRiOWU5ZWEyLWM5ZDEtNDFlZS05YjIxLWRmZDNjM2E1NDI5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxMDA2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODUyMjNiMDAzZjEyZWYxNDc3YmIxYzgyOTk0OGFiZTdiYTMxOTcyNmQxMTE4NThiMTE4MTkyMTFhYzM1NDc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.spagvkEimNjru58cREl2vFeNg7IJuh0eNtoLdWGIZ1g">
> vs https://events.istio.io/istiocon-2021/

Yes, I can see the background image. Note that if you delete `istiocon-2021/` here, the image will gone：https://github.com/istio/istio-events/blob/f82344728557f507966190c36113510b882f5d82/2021/themes/istiocon/assets/scss/_banner.scss#L3

2024-02-29 20:30 UTC, craigbox commented
a better fix would be to put `{{ baseURL }}` into that template but I don't think we need to block on that.

2024-02-29 20:30 UTC, craigbox approved these changes

2024-03-01 20:50 UTC, merged

2024-03-01 21:05 UTC, therealmitchconnors commented
I've merged the change and deployed the code to https://istio-events-4f58c.web.app/
It appears to have some problems, including the content not loading, and the top level menu resulting in 404s.  Since this is a preview site, I'll leave the code merged for now, but we will need additional changes to get this working.

2024-03-04 09:14 UTC, craigbox commented
Did you copy the right folder?
`/istiocon-2021/` seems to be trying to include `https://istio-events-4f58c.web.app/istiocon-2021/livereload.js?mindelay=10&v=2&port=1313&path=istiocon-2021/livereload` which looks like Hugo internals.